version: "3"

services:
    postgres-db:
        container_name: flai-postgres-db
        image: postgres-db:flai
        build:
          context: ./postgres
          args:
            PG_PASSWORD: ${PG_PASSWORD}
            PG_USER: ${PG_USER}
            PG_DB: ${PG_DB}
            DEV_USER: ${DEV_USER}
            DEV_PASSWORD: ${DEV_PASSWORD}
            DEV_DB: ${DEV_DB}
        volumes:
          - ./postgres/pgdata:/var/lib/postgresql/data
        ports:
          - ${POSTGRES_DB_HOST_PORT}:${POSTGRES_DB_CONTAINER_PORT}

    adminer:
        container_name: flai-adminer
        image: adminer
        environment:
          ADMINER_DEFAULT_DB_DRIVER: ${ADMINER_DEFAULT_DB_DRIVER}
          ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
          ADMINER_DEFAULT_USER: ${DEV_USER}
          ADMINER_DESIGN: ${ADMINER_DESIGN}
        ports:
          - ${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}

